/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * FROZEN CONTRACT. The collector, engine, and dashboard are built in parallel against this file. Do not change it without updating fixtures/demo.json in the same commit.
 */
export interface KernelSurfaceLedgerReport {
  meta: {
    kernel_release: string;
    arch: string;
    distro: string;
    collected_at: string;
    trace_seconds: number;
    trace_backend?: 'bcc' | 'perf' | 'strace' | 'none';
    ran_as_root?: boolean;
    /**
     * sources that could not be read, with reasons
     */
    skipped?: {
      source?: string;
      reason?: string;
      [k: string]: unknown;
    }[];
    ksl_version: string;
    [k: string]: unknown;
  };
  surface_elements: {
    id: string;
    kind: 'syscall' | 'module' | 'kconfig' | 'sysctl' | 'devnode' | 'capability' | 'namespace' | 'lsm';
    name: string;
    subsystem?: string;
    weight: number;
    present: boolean;
    reachable_unpriv: boolean;
    used: boolean;
    gate_reason?: string;
    cve_clusters: string[];
    mitigations?: string[];
    [k: string]: unknown;
  }[];
  workloads: {
    id: string;
    comm: string;
    unit?: string;
    pids: number[];
    uid?: number;
    caps_effective?: string[];
    seccomp_mode?: number;
    /**
     * surface_element ids this workload keeps open
     */
    touches: string[];
    [k: string]: unknown;
  }[];
  /**
   * one row per workload, sorted by surface_debt descending
   */
  ledger: {
    workload_id: string;
    surface_debt: number;
    marginal_contribution?: number;
    sole_owner_elements: string[];
    shared_elements: string[];
    reachable_cves: number;
    /**
     * LLM-generated prose. MUST NOT affect any numeric field.
     */
    explanation?: string;
    [k: string]: unknown;
  }[];
  /**
   * Removable surface (kind in syscall, module, devnode, namespace, capability) that is present AND reachable_unpriv AND used by no workload. sysctl, kconfig, and lsm elements are excluded: a misconfigured flag is a missing hardening setting, not orphaned surface, and 'used' is not meaningful for it.
   */
  orphaned: {
    elements: string[];
    total_weight: number;
    cves_neutralizable: number;
    [k: string]: unknown;
  };
  /**
   * greedy set-cover output, ordered by CVE mass killed per unit breakage cost
   */
  plan: {
    step: number;
    action:
      | 'blacklist_module'
      | 'seccomp_filter'
      | 'sysctl_set'
      | 'kconfig_disable'
      | 'systemd_confine'
      | 'remove_devnode_access';
    targets: string[];
    cves_killed: number;
    weight_removed?: number;
    breakage_risk: 'none' | 'low' | 'medium' | 'high';
    breakage_note?: string;
    detection?: string;
    requires_reboot?: boolean;
    artifact: {
      path?: string;
      content?: string;
      [k: string]: unknown;
    };
    revert: string;
    [k: string]: unknown;
  }[];
  score: {
    total_surface_weight: number;
    reachable_surface_weight: number;
    reachable_cve_count: number;
    /**
     * orphaned.total_weight / reachable_surface_weight
     */
    orphan_ratio: number;
    projected_after_plan?: {
      reachable_surface_weight?: number;
      reachable_cve_count?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
