/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PriorArtRouteImport } from './routes/prior-art'
import { Route as SubmissionRouteImport } from './routes/submission'
import { Route as AuthenticatedScansIndexRouteImport } from './routes/_authenticated/scans.index'
import { Route as AuthenticatedScansCompareRouteImport } from './routes/_authenticated/scans.compare'
import { Route as ApiAiAskRouteImport } from './routes/api/ai/ask'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PriorArtRoute = PriorArtRouteImport.update({
  id: '/prior-art',
  path: '/prior-art',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionRoute = SubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScansIndexRoute = AuthenticatedScansIndexRouteImport.update({
  id: '/scans/',
  path: '/scans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScansCompareRoute =
  AuthenticatedScansCompareRouteImport.update({
    id: '/scans/compare',
    path: '/scans/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAiAskRoute = ApiAiAskRouteImport.update({
  id: '/api/ai/ask',
  path: '/api/ai/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/prior-art': typeof PriorArtRoute
  '/submission': typeof SubmissionRoute
  '/scans/compare': typeof AuthenticatedScansCompareRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/scans/': typeof AuthenticatedScansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/prior-art': typeof PriorArtRoute
  '/submission': typeof SubmissionRoute
  '/scans/compare': typeof AuthenticatedScansCompareRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/scans': typeof AuthenticatedScansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pipeline': typeof PipelineRoute
  '/prior-art': typeof PriorArtRoute
  '/submission': typeof SubmissionRoute
  '/_authenticated/scans/compare': typeof AuthenticatedScansCompareRoute
  '/api/ai/ask': typeof ApiAiAskRoute
  '/_authenticated/scans/': typeof AuthenticatedScansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/pipeline'
    | '/prior-art'
    | '/submission'
    | '/scans/compare'
    | '/api/ai/ask'
    | '/scans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/pipeline'
    | '/prior-art'
    | '/submission'
    | '/scans/compare'
    | '/api/ai/ask'
    | '/scans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how-it-works'
    | '/pipeline'
    | '/prior-art'
    | '/submission'
    | '/_authenticated/scans/compare'
    | '/api/ai/ask'
    | '/_authenticated/scans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PipelineRoute: typeof PipelineRoute
  PriorArtRoute: typeof PriorArtRoute
  SubmissionRoute: typeof SubmissionRoute
  ApiAiAskRoute: typeof ApiAiAskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prior-art': {
      id: '/prior-art'
      path: '/prior-art'
      fullPath: '/prior-art'
      preLoaderRoute: typeof PriorArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission': {
      id: '/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scans/': {
      id: '/_authenticated/scans/'
      path: '/scans'
      fullPath: '/scans/'
      preLoaderRoute: typeof AuthenticatedScansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scans/compare': {
      id: '/_authenticated/scans/compare'
      path: '/scans/compare'
      fullPath: '/scans/compare'
      preLoaderRoute: typeof AuthenticatedScansCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai/ask': {
      id: '/api/ai/ask'
      path: '/api/ai/ask'
      fullPath: '/api/ai/ask'
      preLoaderRoute: typeof ApiAiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedScansCompareRoute: typeof AuthenticatedScansCompareRoute
  AuthenticatedScansIndexRoute: typeof AuthenticatedScansIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedScansCompareRoute: AuthenticatedScansCompareRoute,
  AuthenticatedScansIndexRoute: AuthenticatedScansIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  PipelineRoute: PipelineRoute,
  PriorArtRoute: PriorArtRoute,
  SubmissionRoute: SubmissionRoute,
  ApiAiAskRoute: ApiAiAskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
